<script>
import Vue from "vue";
import { GTButton } from "@/entry.esm";

export default Vue.extend({
  name: "ButtonsList",
  components: {
    GTButton,
  },
});
</script>

<template>
  <div>
    <p class="mt--10 ml--20 playfair playfair--h5">Primary Buttons</p>
    <div class="mt--5 mb--15 grid--container">
      <div class="grid--row">
        <div class="grid--col-lg-12">
          <GTButton type="primary" variant="sea-foam" size="sm" text="Button" />
          <GTButton
            class="ml--5"
            isDisabled
            type="primary"
            size="sm"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            size="sm"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="primary"
            size="sm"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            size="sm"
            isPrependIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            size="sm"
            isAppendIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            isLoading
            size="sm"
          />
        </div>
        <div class="grid--col-lg-12">
          <GTButton type="primary" variant="sea-foam" size="md" text="Button" />
          <GTButton
            class="ml--5"
            isDisabled
            type="primary"
            variant="sea-foam"
            size="md"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            size="md"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="primary"
            size="md"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            size="md"
            isPrependIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            size="md"
            isAppendIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            isLoading
            size="md"
          />
        </div>
        <div class="grid--col-lg-12">
          <GTButton type="primary" variant="sea-foam" size="lg" text="Button" />
          <GTButton
            class="ml--5"
            isDisabled
            type="primary"
            size="lg"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            size="lg"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="primary"
            size="lg"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            type="primary"
            variant="sea-foam"
            size="lg"
            isPrependIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
        </div>
        <div class="grid--row">
          <div class="grid--col-lg-12">
            <GTButton
              type="primary"
              size="lg"
              variant="sea-foam"
              isAppendIcon
              icon="gt-paper-plane-s"
              text="Button"
            />
            <GTButton
              class="ml--5"
              type="primary"
              variant="sea-foam"
              isLoading
              size="lg"
            />
          </div>
        </div>
      </div>
    </div>
    <p class="mt--10 ml--20 playfair playfair--h5">Secondary Buttons</p>
    <div class="mt--5 mb--15 grid--container">
      <div class="grid--row">
        <div class="grid--col-lg-12">
          <GTButton
            type="secondary"
            variant="chocolate"
            size="sm"
            text="Button"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="secondary"
            size="sm"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            size="sm"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="secondary"
            size="sm"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            size="sm"
            isPrependIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            size="sm"
            isAppendIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            isLoading
            size="sm"
          />
        </div>
        <div class="grid--col-lg-12">
          <GTButton
            type="secondary"
            variant="chocolate"
            size="md"
            text="Button"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="secondary"
            size="md"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            size="md"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="secondary"
            size="md"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            size="md"
            isPrependIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            size="md"
            isAppendIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            isLoading
            size="md"
          />
        </div>
        <div class="grid--col-lg-12">
          <GTButton
            type="secondary"
            variant="chocolate"
            size="lg"
            text="Button"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="secondary"
            size="lg"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            size="lg"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="secondary"
            size="lg"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            size="lg"
            isPrependIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
        </div>
        <div class="grid--col-lg-12">
          <GTButton
            type="secondary"
            variant="chocolate"
            size="lg"
            isAppendIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="secondary"
            variant="chocolate"
            isLoading
            size="lg"
          />
        </div>
      </div>
    </div>
    <p class="mt--10 ml--20 playfair playfair--h5">Tertiary Buttons</p>
    <div class="mt--5 mb--15 grid--container">
      <div class="grid--row">
        <div class="grid--col-lg-12">
          <GTButton type="link" variant="error" size="sm" text="Button" />
          <GTButton
            class="ml--5"
            isDisabled
            type="link"
            size="sm"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            size="sm"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="link"
            size="sm"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            size="sm"
            isPrependIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            size="sm"
            isAppendIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            isLoading
            size="sm"
          />
        </div>
        <div class="grid--col-lg-12">
          <GTButton type="link" variant="error" size="md" text="Button" />
          <GTButton
            class="ml--5"
            isDisabled
            type="link"
            size="md"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            size="md"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="link"
            size="md"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            size="md"
            isPrependIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            size="md"
            isAppendIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            isLoading
            size="md"
          />
        </div>
        <div class="grid--col-lg-12">
          <GTButton type="link" variant="error" size="lg" text="Button" />
          <GTButton
            class="ml--5"
            isDisabled
            type="link"
            size="lg"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            size="lg"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            isDisabled
            type="link"
            size="lg"
            icon="gt-paper-plane-s"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            size="lg"
            isPrependIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
        </div>
        <div class="grid--col-lg-12">
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            size="lg"
            isAppendIcon
            icon="gt-paper-plane-s"
            text="Button"
          />
          <GTButton
            class="ml--5"
            type="link"
            variant="error"
            isLoading
            size="lg"
          />
        </div>
      </div>
    </div>
  </div>
</template>
